// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZyX-koxCkT5H40qD0HjWlcqdJgFnEHo4',
    appId: '1:176161723550:web:6b551ca6cccb18b9e8178f',
    messagingSenderId: '176161723550',
    projectId: 'eva-testing-85a6b',
    authDomain: 'eva-testing-85a6b.firebaseapp.com',
    storageBucket: 'eva-testing-85a6b.appspot.com',
    measurementId: 'G-7BRWZPXWG3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1pwZw_q6hMi4Qkw-oEJh8VkrHYMGMVDI',
    appId: '1:176161723550:android:b2a2fc3676c98cb3e8178f',
    messagingSenderId: '176161723550',
    projectId: 'eva-testing-85a6b',
    storageBucket: 'eva-testing-85a6b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQbpaWWCU_VQwp9fxMSC2sJZKldS-IUPQ',
    appId: '1:176161723550:ios:23a059a807f57befe8178f',
    messagingSenderId: '176161723550',
    projectId: 'eva-testing-85a6b',
    storageBucket: 'eva-testing-85a6b.appspot.com',
    iosBundleId: 'com.example.evaProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQbpaWWCU_VQwp9fxMSC2sJZKldS-IUPQ',
    appId: '1:176161723550:ios:23a059a807f57befe8178f',
    messagingSenderId: '176161723550',
    projectId: 'eva-testing-85a6b',
    storageBucket: 'eva-testing-85a6b.appspot.com',
    iosBundleId: 'com.example.evaProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZyX-koxCkT5H40qD0HjWlcqdJgFnEHo4',
    appId: '1:176161723550:web:aa5ddf3b39367f9ee8178f',
    messagingSenderId: '176161723550',
    projectId: 'eva-testing-85a6b',
    authDomain: 'eva-testing-85a6b.firebaseapp.com',
    storageBucket: 'eva-testing-85a6b.appspot.com',
    measurementId: 'G-V40EJ57BZD',
  );

}